 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cookbook/recipes", type: :request do
  
  # Cookbook::Recipe. As you add validations to Cookbook::Recipe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cookbook::Recipe.create! valid_attributes
      get cookbook_recipes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      recipe = Cookbook::Recipe.create! valid_attributes
      get cookbook_recipe_url(cookbook_recipe)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cookbook_recipe_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      recipe = Cookbook::Recipe.create! valid_attributes
      get edit_cookbook_recipe_url(cookbook_recipe)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cookbook::Recipe" do
        expect {
          post cookbook_recipes_url, params: { cookbook_recipe: valid_attributes }
        }.to change(Cookbook::Recipe, :count).by(1)
      end

      it "redirects to the created cookbook_recipe" do
        post cookbook_recipes_url, params: { cookbook_recipe: valid_attributes }
        expect(response).to redirect_to(cookbook_recipe_url(@cookbook_recipe))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cookbook::Recipe" do
        expect {
          post cookbook_recipes_url, params: { cookbook_recipe: invalid_attributes }
        }.to change(Cookbook::Recipe, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cookbook_recipes_url, params: { cookbook_recipe: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cookbook_recipe" do
        recipe = Cookbook::Recipe.create! valid_attributes
        patch cookbook_recipe_url(cookbook_recipe), params: { cookbook_recipe: new_attributes }
        recipe.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cookbook_recipe" do
        recipe = Cookbook::Recipe.create! valid_attributes
        patch cookbook_recipe_url(cookbook_recipe), params: { cookbook_recipe: new_attributes }
        recipe.reload
        expect(response).to redirect_to(cookbook_recipe_url(recipe))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        recipe = Cookbook::Recipe.create! valid_attributes
        patch cookbook_recipe_url(cookbook_recipe), params: { cookbook_recipe: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cookbook_recipe" do
      recipe = Cookbook::Recipe.create! valid_attributes
      expect {
        delete cookbook_recipe_url(cookbook_recipe)
      }.to change(Cookbook::Recipe, :count).by(-1)
    end

    it "redirects to the cookbook_recipes list" do
      recipe = Cookbook::Recipe.create! valid_attributes
      delete cookbook_recipe_url(cookbook_recipe)
      expect(response).to redirect_to(cookbook_recipes_url)
    end
  end
end
